version = 0.1

[default]
[default.global.parameters]
stack_name = "as-whatsapp-agent"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
resolve_s3 = true
image_repositories = []

[default.build.parameters]
use_container = false

[default.deploy.parameters]
stack_name = "as-whatsapp-agent"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
resolve_s3 = true
